apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-vruhlfek
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-vruhlfek:746155adf0110b7fe155573de2df5624a215a14b@sha256:094e6d0487a7e8c303075e91d794e5ba9a4af320582735741dc3f521a6910b53
        name: container-image  
